apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000S
    - port: 50000
      targetPort: 50000
      nodePort: 30001
  selector:
    app: jenkins
