apiVersion: v1
kind: Secret
metadata:
  name: pod-reader-sa-token
  annotations:
    kubernetes.io/service-account.name: "pod-reader"
type: kubernetes.io/service-account-token

#kubectl create secret generic pod-reader-sa-token --from-literal=token=$(head -c 16 /dev/urandom | base64) --type=kubernetes.io/service-account-token --dry-run=client -o yaml > secret.yml
#kubectl patch serviceaccount pod-reader-sa -p '{"secrets":[{"name":"pod-reader-sa-token"}]}'
