apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: nti
data:
  database: my_database
  user: my_user

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: nti
type: Opaque
data:
  root_password: bXd0
  user_password: bXd0

