apiVersion: v1
kind: Pod
metadata:
  name: toleration-pod
spec:
  tolerations:
  - key: color
    operator: Equal
    value: "red"  
  containers:
  - name: busybox
    image: busybox:latest
    command: ["sleep", "infinity"]

