---
- name: Download the OpenShift CLI
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz
    dest: /tmp/openshift-client-linux.tar.gz

- name: Extract the OpenShift CLI
  unarchive:
    src: /tmp/openshift-client-linux.tar.gz
    dest: /usr/local/bin
    creates: /usr/local/bin/oc
    remote_src: yes

- name: Ensure OpenShift CLI is executable
  file:
    path: /usr/local/bin/oc
    mode: '0755'
    state: file

